[package]
name = "upgrade"
version = "0.0.0"
workspace = "../"
edition = "2021"
publish = false

[dependencies]
rocket = { package = "rocket-community", path = "../../core/lib" }
ws = { package = "rocket_ws-community", path = "../../contrib/ws" }
