[package]
name = "rocket-benchmarks-community"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[[bench]]
name = "main"
path = "src/bench.rs"
harness = false

[dev-dependencies]
rocket = { package = "rocket-community", path = "../core/lib/" }
criterion = "0.5.1"
